"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import { startSpeechRecognition, splitIntoSentences, AudioRecorder } from "@/lib/speech";
import { AudioQueue } from "@/lib/audio-queue";

interface RoomAvatar {
  id: string;
  name: string;
  avatar_url: string;
}

interface Participant {
  id: string;
  name: string;
  avatar?: string;
  bio?: string;
  type: "human" | "ai";
}

interface OrchestrateResponse {
  avatar_name: string;
  strategy: "short_reply" | "deep_discuss" | "ask_question" | "summarize" | "pass";
  max_sentences: number;
}

function buildSystemPrompt(strategy: string, maxSentences: number): string {
  const base = "你是一位会议参与者。";
  switch (strategy) {
    case "short_reply":
      return `${base}简短回应，最多${maxSentences}句话。不要展开论述，像随意聊天一样。`;
    case "deep_discuss":
      return `${base}深入讨论这个话题，分享你的见解和经验，控制在${maxSentences}句以内。`;
    case "ask_question":
      return `${base}针对当前讨论提出一个有价值的问题，引导更深入的思考。最多${maxSentences}句。`;
    case "summarize":
      return `${base}简要总结目前的讨论要点，最多${maxSentences}句。`;
    default:
      return `${base}自然参与讨论，控制在2-3句话。如果没有有价值的补充，回复 [PASS]。`;
  }
}

interface Message {
  id: number;
  senderId: string;
  sender: string;
  senderType: "human" | "ai";
  text: string;
  timestamp: number;
}

function getCookie(name: string) {
  if (typeof document === "undefined") return null;
  const match = document.cookie.match(new RegExp(`(^| )${name}=([^;]+)`));
  return match ? decodeURIComponent(match[2]) : null;
}

// Static SYSTEM_PROMPT removed — now dynamically generated by buildSystemPrompt()

export default function RoomPage() {
  const { roomId } = useParams<{ roomId: string }>();
  const router = useRouter();
  const [topic, setTopic] = useState("");
  const [user, setUser] = useState<{ name: string; avatar: string } | null>(null);
  const [aiParticipants, setAiParticipants] = useState<Participant[]>([]);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isListening, setIsListening] = useState(false);
  const [interimText, setInterimText] = useState("");
  const [textEditing, setTextEditing] = useState(false);
  const [editText, setEditText] = useState("");
  const [sentFlash, setSentFlash] = useState(false);
  const [activeAiId, setActiveAiId] = useState<string | null>(null); // thinking, streaming, or playing
  const [activePhase, setActivePhase] = useState<"idle" | "thinking" | "streaming" | "playing">("idle");
  const [aiStreamText, setAiStreamText] = useState("");
  const [playingSentenceIdx, setPlayingSentenceIdx] = useState(-1);
  const [bubbleOverflow, setBubbleOverflow] = useState(false);
  const sentencesRef = useRef<string[]>([]);
  const bubbleRef = useRef<HTMLDivElement>(null);

  // Scroll to highlighted sentence when it changes
  useEffect(() => {
    if (bubbleRef.current && playingSentenceIdx >= 0) {
      const el = bubbleRef.current.querySelector(`[data-idx="${playingSentenceIdx}"]`);
      el?.scrollIntoView({ block: "center", behavior: "smooth" });
    }
  }, [playingSentenceIdx]);

  // Check if bubble has overflow
  useEffect(() => {
    const el = bubbleRef.current;
    if (el) {
      setBubbleOverflow(el.scrollHeight > el.clientHeight + 4);
    }
  }, [aiStreamText, activeAiId, playingSentenceIdx]);

  const recognitionRef = useRef<ReturnType<typeof startSpeechRecognition>>(null);
  const audioQueueRef = useRef<AudioQueue>(new AudioQueue());
  const msgIdRef = useRef(0);
  const sessionMapRef = useRef<Record<string, string | undefined>>({});
  const abortRef = useRef<AbortController | null>(null);
  const askingRef = useRef(false);
  const messagesRef = useRef<Message[]>([]);
  const mountedRef = useRef(true);
  const recorderRef = useRef<AudioRecorder>(new AudioRecorder());

  const saveMessage = useCallback((msg: { sender_id: string; sender_name: string; sender_type: string; content: string; tts_audio_url?: string }) => {
    fetch(`/api/rooms/${roomId}/messages`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(msg),
    }).catch(() => {});
  }, [roomId]);

  // Load room data
  useEffect(() => {
    mountedRef.current = true;

    const raw = getCookie("sm_user");
    if (raw) {
      try { setUser(JSON.parse(raw)); } catch { /* */ }
    }

    fetch(`/api/rooms/${roomId}`)
      .then((r) => r.json())
      .then((room) => {
        if (!mountedRef.current) return;
        if (room.error) { setTopic("自由讨论"); return; }
        setTopic(room.topic || "自由讨论");

        const stored: RoomAvatar[] = room.avatar_participants || [];
        setAiParticipants(stored.map((a) => ({
          id: a.id, name: a.name, avatar: a.avatar_url, type: "ai" as const,
        })));
      })
      .catch(() => setTopic("自由讨论"));

    // Load history messages
    fetch(`/api/rooms/${roomId}/messages`)
      .then((r) => r.json())
      .then((data) => {
        if (!mountedRef.current) return;
        if (Array.isArray(data) && data.length > 0) {
          const loaded: Message[] = data.map((d: { id: number; sender_id: string; sender_name: string; sender_type: "human" | "ai"; content: string; created_at: string }, i: number) => ({
            id: i + 1,
            senderId: d.sender_id,
            sender: d.sender_name,
            senderType: d.sender_type,
            text: d.content,
            timestamp: new Date(d.created_at).getTime(),
          }));
          setMessages(loaded);
          messagesRef.current = loaded;
          msgIdRef.current = loaded.length;
        }
      })
      .catch(() => {});

    return () => {
      mountedRef.current = false;
      abortRef.current?.abort();
      audioQueueRef.current.stop();
    };
  }, [roomId]);

  const askAIs = useCallback(async (allMessages: Message[]) => {
    if (askingRef.current) return;
    askingRef.current = true;

    try {
      // --- Step 1: Ask Gemini who should speak and how ---
      let plan: OrchestrateResponse[] = [];
      try {
        const orchestrateRes = await fetch("/api/orchestrate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            topic,
            messages: allMessages.slice(-15).map((m) => ({ sender: m.sender, text: m.text })),
            avatars: aiParticipants.map((a) => ({ name: a.name, bio: a.bio || "" })),
          }),
        });
        const orchestrateData = await orchestrateRes.json();
        plan = orchestrateData.responses || [];
      } catch {
        // Fallback: all avatars respond
        plan = aiParticipants.map((a) => ({ avatar_name: a.name, strategy: "short_reply" as const, max_sentences: 3 }));
      }

      // --- Step 2: Execute plan — each avatar speaks in order ---
      for (const response of plan) {
        if (response.strategy === "pass") continue;
        if (!mountedRef.current) break;

        const ai = aiParticipants.find((a) => a.name === response.avatar_name);
        if (!ai) continue;

        const systemPrompt = buildSystemPrompt(response.strategy, response.max_sentences);

        // Clean slate for this avatar's audio
        audioQueueRef.current.stop();

        setActiveAiId(ai.id);
        setActivePhase("thinking");
        setAiStreamText("");
        setPlayingSentenceIdx(-1);

        // Build context from ALL messages including previous AI replies in this round
        const context = allMessages
          .slice(-15)
          .map((m) => `${m.sender}: ${m.text}`)
          .join("\n");

        // Tell the AI who already spoke in this round so it doesn't repeat
        const alreadySpoke = plan
          .slice(0, plan.indexOf(response))
          .filter((r) => r.strategy !== "pass")
          .map((r) => r.avatar_name);
        const spokenNote = alreadySpoke.length > 0
          ? `\n\n注意：在你之前，${alreadySpoke.join("、")}已经回应了（见上方对话）。不要重复他们说过的内容，也不要再把话题抛给他们。直接回应最新的讨论。`
          : "";

        const prompt = `会议主题: ${topic}\n\n最近的对话:\n${context}${spokenNote}\n\n请根据以上对话自然参与讨论。`;

        const controller = new AbortController();
        abortRef.current = controller;

        try {
          const res = await fetch("/api/chat/stream", {
            signal: controller.signal,
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              message: prompt,
              sessionId: sessionMapRef.current[ai.id],
              systemPrompt,
              avatarId: ai.id,
            }),
          });

          if (!res.ok || !res.body) {
            setActiveAiId(null);
            setActivePhase("idle");
            continue;
          }

          // --- Pipelined: stream text + fire TTS as sentences complete ---
          const reader = res.body.getReader();
          const decoder = new TextDecoder();
          let fullText = "";
          let buffer = "";
          let ttsIndex = 0;
          const ttsPromises: Promise<void>[] = [];

          const queue = audioQueueRef.current;
          queue.onPlay = (idx) => setPlayingSentenceIdx(idx);

          const fireTTS = (sentence: string, index: number) => {
            const p = fetch("/api/tts", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ text: sentence, avatarId: ai.id }),
            })
              .then((r) => r.json())
              .then((ttsData) => {
                const url = ttsData.data?.audioUrl || ttsData.data?.url;
                if (url && mountedRef.current) {
                  queue.enqueue(url, index);
                  if (!queue.isPlaying()) {
                    setActivePhase("playing");
                    queue.startPlayback();
                  }
                }
              })
              .catch(() => {});
            ttsPromises.push(p);
          };

          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\n");
            buffer = lines.pop() || "";

            for (const line of lines) {
              if (line.startsWith("data: ")) {
                const data = line.slice(6).trim();
                if (data === "[DONE]") continue;
                try {
                  const parsed = JSON.parse(data);
                  if (parsed.sessionId) sessionMapRef.current[ai.id] = parsed.sessionId;
                  const chunk = parsed.choices?.[0]?.delta?.content || "";
                  if (chunk) {
                    fullText += chunk;
                    setAiStreamText(fullText);
                    setActivePhase("streaming");

                    // Fire TTS for each newly completed sentence
                    const currentSentences = splitIntoSentences(fullText);
                    while (ttsIndex < currentSentences.length - 1) {
                      fireTTS(currentSentences[ttsIndex], ttsIndex);
                      ttsIndex++;
                    }
                  }
                } catch { /* skip */ }
              }
            }
          }

          // Fire TTS for the last sentence
          const finalSentences = splitIntoSentences(fullText);
          while (ttsIndex < finalSentences.length) {
            fireTTS(finalSentences[ttsIndex], ttsIndex);
            ttsIndex++;
          }
          sentencesRef.current = finalSentences;

          // Skip if PASS or empty
          if (fullText.trim() === "[PASS]" || fullText.trim() === "") {
            setActiveAiId(null);
            setActivePhase("idle");
            setAiStreamText("");
            continue;
          }

          // Add message to list
          const aiMsg: Message = {
            id: ++msgIdRef.current,
            senderId: ai.id,
            sender: ai.name,
            senderType: "ai",
            text: fullText,
            timestamp: Date.now(),
          };
          messagesRef.current = [...messagesRef.current, aiMsg];
          setMessages(messagesRef.current);
          allMessages = [...allMessages, aiMsg];
          setAiStreamText("");

          // Save to DB
          saveMessage({ sender_id: ai.id, sender_name: ai.name, sender_type: "ai", content: fullText });

          // Wait for all TTS requests to finish, then seal queue and wait for playback
          await Promise.all(ttsPromises);

          // Wait for all TTS to arrive, then wait for playback to finish
          if (mountedRef.current && (queue.isPlaying() || queue.hasItems())) {
            await new Promise<void>((resolve) => {
              queue.onFinish = () => {
                if (mountedRef.current) setPlayingSentenceIdx(-1);
                resolve(); // Don't clear activeAiId here — let the for loop handle it
              };
              queue.seal();
            });
          } else {
            setPlayingSentenceIdx(-1);
          }

        } catch (err) {
          if (err instanceof DOMException && err.name === "AbortError") {
            // User stopped — don't reset activeAiId here, stopAI handles it
          } else {
            setActiveAiId(null);
            setActivePhase("idle");
            setAiStreamText("");
          }
        }
      }
      // All avatars done
      setActiveAiId(null);
      setActivePhase("idle");
    } finally {
      askingRef.current = false;
    }
  }, [aiParticipants, topic, saveMessage]);

  const stopAI = () => {
    askingRef.current = false;
    abortRef.current?.abort();
    abortRef.current = null;
    audioQueueRef.current.stop();
    setActiveAiId(null);
    setActivePhase("idle");
    setPlayingSentenceIdx(-1);
    setAiStreamText("");
  };

  const uploadAudio = async (blob: Blob): Promise<string | undefined> => {
    if (blob.size < 1000) return undefined; // Skip tiny recordings
    try {
      const form = new FormData();
      form.append("file", blob, "recording.webm");
      form.append("roomId", roomId);
      const res = await fetch("/api/audio", { method: "POST", body: form });
      const data = await res.json();
      return data.url;
    } catch { return undefined; }
  };

  const sendHumanMessage = (text: string) => {
    if (!text.trim()) return;
    // Interrupt AI if active
    if (askingRef.current || activePhase !== "idle") stopAI();
    // Flash "已发送"
    setSentFlash(true);
    setTimeout(() => setSentFlash(false), 1500);
    const msg: Message = {
      id: ++msgIdRef.current,
      senderId: user?.name || "me",
      sender: user?.name || "Me",
      senderType: "human",
      text: text.trim(),
      timestamp: Date.now(),
    };
    saveMessage({ sender_id: user?.name || "me", sender_name: user?.name || "Me", sender_type: "human", content: text.trim() });
    messagesRef.current = [...messagesRef.current, msg];
    setMessages(messagesRef.current);
    setTimeout(() => askAIs(messagesRef.current), 500);
  };

  const toggleMic = async () => {
    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
      // Stop recording — audio will be uploaded with the last final message
      const blob = await recorderRef.current.stop();
      // Upload in background if there's a pending message
      if (blob.size > 1000) {
        uploadAudio(blob).then((url) => {
          if (url) {
            // Update the last human message in DB with audio URL
            // (fire and forget)
            fetch(`/api/rooms/${roomId}/messages`, {
              method: "PATCH",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ lastHumanAudioUrl: url }), // Legacy — uses last-human lookup
            }).catch(() => {});
          }
        });
      }
      return;
    }
    // Interrupt AI if it's speaking
    if (activePhase !== "idle") stopAI();
    setIsListening(true);
    // Start audio recording alongside speech recognition
    recorderRef.current.start().catch(() => {});
    recognitionRef.current = startSpeechRecognition(
      (text, isFinal) => {
        if (isFinal && text.trim()) {
          sendHumanMessage(text.trim());
          setInterimText("");
        } else {
          setInterimText(text);
        }
      },
      () => setIsListening(false)
    );
  };

  const getAiPosition = (index: number, total: number) => {
    const spacing = 100 / (total + 1);
    return { left: `${spacing * (index + 1)}%` };
  };

  const getLatestMessage = (participantId: string) => {
    return [...messages].reverse().find((m) => m.senderId === participantId);
  };

  const endRoom = async () => {
    await fetch(`/api/rooms/${roomId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: "ended", ended_at: new Date().toISOString() }),
    });
    recognitionRef.current?.stop();
    audioQueueRef.current.stop();
    router.push("/");
  };

  return (
    <main className="h-screen w-screen overflow-hidden relative bg-[#FEF3E2]">
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-0 left-1/4 w-[400px] h-[400px] bg-[#9B5DE5]/4 rounded-full blur-[120px]" />
        <div className="absolute top-1/4 right-1/4 w-[350px] h-[350px] bg-[#F4A261]/5 rounded-full blur-[100px]" />
      </div>

      {/* Topic bar */}
      <div className="absolute top-0 left-0 right-0 z-20 px-5 py-3 flex items-start justify-between">
        <div>
          <p className="text-[#3D2C1E]/60 text-sm font-medium">{topic}</p>
          <p className="text-[#3D2C1E]/25 text-[10px]">房间 {roomId} · {aiParticipants.length} 个分身</p>
        </div>
        <button
          onClick={endRoom}
          className="shrink-0 mt-0.5 px-3 py-1 rounded-full text-[10px] text-[#E76F51]/50 hover:text-[#E76F51] hover:bg-[#E76F51]/8 transition-colors"
        >
          结束会议
        </button>
      </div>

      {/* No avatars hint */}
      {aiParticipants.length === 0 && (
        <div className="absolute top-1/3 left-0 right-0 text-center z-10">
          <p className="text-[#3D2C1E]/20 text-sm">还没有分身参会</p>
          <p className="text-[#3D2C1E]/15 text-xs mt-1">回首页选择分身后再创建会议</p>
        </div>
      )}

      {/* AI participants */}
      <div className="absolute top-16 left-0 right-0 px-8" style={{ height: "55%" }}>
        <div className="relative w-full h-full">
          {aiParticipants.map((ai, i) => {
            const pos = getAiPosition(i, aiParticipants.length);
            const isActive = activeAiId === ai.id;
            const isThinking = isActive && activePhase === "thinking";
            const isStreaming = isActive && activePhase === "streaming";
            const isPlaying = isActive && activePhase === "playing";
            const latestMsg = getLatestMessage(ai.id);
            const showStream = isStreaming && aiStreamText;

            return (
              <div
                key={ai.id}
                className="absolute -translate-x-1/2 flex flex-col items-center"
                style={{ left: pos.left, top: "15%" }}
              >
                <div
                  className={`
                    w-16 h-16 rounded-full flex items-center justify-center text-xl font-bold overflow-hidden
                    bg-[#9B5DE5]/15 border-2 transition-all duration-500
                    ${isThinking ? "border-[#9B5DE5]/50 animate-ai-thinking" : ""}
                    ${isStreaming || isPlaying ? "border-[#9B5DE5]/60 animate-speaking scale-105" : ""}
                    ${!isActive ? "border-[#9B5DE5]/20 animate-breathe" : ""}
                  `}
                >
                  {ai.avatar ? (
                    <img src={ai.avatar} alt={ai.name} className="w-full h-full rounded-full object-cover" onError={(e) => { e.currentTarget.style.display = "none"; e.currentTarget.parentElement!.textContent = ai.name[0]; }} />
                  ) : (
                    <span className="text-[#9B5DE5]/60">{ai.name[0]}</span>
                  )}
                </div>
                <span className="text-[10px] text-[#9B5DE5]/50 mt-1.5">{ai.name}</span>

                {/* Stop button — visible during all active phases */}
                {isActive && activePhase !== "idle" && (
                  <button
                    onClick={stopAI}
                    className="mt-1.5 w-6 h-6 rounded-full bg-white/70 hover:bg-white text-[#E76F51]/50 hover:text-[#E76F51] flex items-center justify-center transition-colors shadow-sm"
                  >
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor">
                      <rect x="6" y="6" width="12" height="12" rx="2" />
                    </svg>
                  </button>
                )}

                {isThinking && (
                  <div className="mt-2 dot-pulse text-[#9B5DE5]/40 text-lg">
                    <span>·</span><span>·</span><span>·</span>
                  </div>
                )}

                {(showStream || latestMsg) && (
                  <div className="mt-2 max-w-[320px] w-[280px] relative">
                    <div
                      ref={isActive ? bubbleRef : undefined}
                      className={`max-h-[200px] overflow-y-auto backdrop-blur-sm rounded-2xl px-4 py-3 text-sm animate-fade-in leading-relaxed transition-all duration-500 ${
                        isActive ? "bg-white/60 text-[#3D2C1E]/70" : "bg-white/30 text-[#3D2C1E]/35"
                      }`}
                    >
                      {showStream ? aiStreamText : (
                        isPlaying && playingSentenceIdx >= 0
                          ? sentencesRef.current.map((s, si) => (
                              <span key={si} data-idx={si} className={si === playingSentenceIdx ? "text-[#9B5DE5] font-medium" : ""}>{s}{" "}</span>
                            ))
                          : latestMsg?.text
                      )}
                    </div>
                    {isActive && bubbleOverflow && (
                      <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-white/60 to-transparent rounded-b-2xl pointer-events-none flex items-end justify-center pb-1">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-[#9B5DE5]/30">
                          <polyline points="6 9 12 15 18 9" />
                        </svg>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Human area */}
      <div className="absolute bottom-0 left-0 right-0 z-10 flex flex-col items-center pb-8">
        {/* Text input/display area */}
        <div className="mb-4 max-w-[320px] w-[280px]">
          {textEditing ? (
            <div className="bg-white/70 backdrop-blur-sm rounded-2xl px-3 py-2 flex items-end gap-2 shadow-sm border border-[#F4A261]/20">
              <textarea
                value={editText}
                onChange={(e) => { setEditText(e.target.value); e.target.style.height = "auto"; e.target.style.height = Math.min(e.target.scrollHeight, 120) + "px"; }}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey && editText.trim()) {
                    e.preventDefault();
                    sendHumanMessage(editText.trim());
                    setEditText("");
                    setTextEditing(false);
                  }
                  if (e.key === "Escape") {
                    setEditText("");
                    setTextEditing(false);
                  }
                }}
                autoFocus
                rows={1}
                placeholder="输入消息..."
                className="flex-1 bg-transparent text-sm text-[#3D2C1E]/70 outline-none placeholder:text-[#3D2C1E]/20 resize-none leading-relaxed"
              />
              <button
                onClick={() => { setEditText(""); setTextEditing(false); }}
                className="shrink-0 w-6 h-6 rounded-full text-[#3D2C1E]/20 hover:text-[#3D2C1E]/50 hover:bg-[#3D2C1E]/5 flex items-center justify-center transition-colors text-xs"
              >
                ×
              </button>
              <button
                onClick={() => {
                  if (editText.trim()) {
                    sendHumanMessage(editText.trim());
                    setEditText("");
                    setTextEditing(false);
                  }
                }}
                disabled={!editText.trim()}
                className="shrink-0 w-7 h-7 rounded-full bg-[#F4A261] text-white flex items-center justify-center disabled:opacity-30 hover:bg-[#e5934f] transition-colors"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <line x1="22" y1="2" x2="11" y2="13" />
                  <polygon points="22 2 15 22 11 13 2 9 22 2" />
                </svg>
              </button>
            </div>
          ) : (
            <div
              className="bg-white/40 backdrop-blur-sm rounded-2xl px-4 py-2.5 text-sm text-center cursor-text min-h-[40px] flex items-center justify-center"
              onClick={() => {
                setTextEditing(true);
                setEditText(interimText || "");
              }}
            >
              {sentFlash ? (
                <span className="text-[#F4A261]/70 animate-fade-in text-xs font-medium">已发送</span>
              ) : (
                <span className={interimText ? "text-[#3D2C1E]/60 animate-fade-in" : "text-[#3D2C1E]/20"}>
                  {interimText || getLatestMessage(user?.name || "me")?.text || "点击输入..."}
                </span>
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-4">
          <div
            className={`
              w-14 h-14 rounded-full flex items-center justify-center text-lg font-bold overflow-hidden
              bg-[#F4A261]/15 border-2 transition-all duration-300
              ${isListening ? "border-[#F4A261] animate-speaking scale-105" : "border-[#F4A261]/25"}
            `}
          >
            {user?.avatar ? (
              <img src={user.avatar} alt={user.name} className="w-full h-full rounded-full object-cover" />
            ) : (
              <span className="text-[#F4A261]/60">{user?.name?.[0] || "?"}</span>
            )}
          </div>

          <button
            onClick={toggleMic}
            className={`
              w-14 h-14 rounded-full flex items-center justify-center transition-all duration-300 shadow-lg
              ${isListening
                ? "bg-[#E76F51] text-white animate-pulse-glow scale-110 shadow-[#E76F51]/30"
                : "bg-white/70 text-[#3D2C1E]/40 hover:bg-white hover:text-[#3D2C1E]/60 shadow-black/5"
              }
            `}
          >
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              {isListening ? (
                <rect x="6" y="6" width="12" height="12" rx="2" />
              ) : (
                <>
                  <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                  <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                  <line x1="12" y1="19" x2="12" y2="23" />
                  <line x1="8" y1="23" x2="16" y2="23" />
                </>
              )}
            </svg>
          </button>

          <span className="text-xs text-[#3D2C1E]/30">{user?.name || ""}</span>
        </div>

        {messages.length === 0 && !isListening && (
          <p className="mt-3 text-[#3D2C1E]/15 text-[11px]">点击麦克风开始发言</p>
        )}
      </div>
    </main>
  );
}
